from colours import *

FPS = 60

MAX_X, MAX_Y = 1200, 700
BORDER = 100

MAX_RADIUS = 70
MIN_RADIUS = 30
MAX_SPEED = 500
MAX_V = MAX_SPEED * (2 ** 0.5)

PALETTE = [RED, BLUE, YELLOW, GREEN, MAGENTA, CYAN]
NUM_COLOURS = 6
DEFAULT_COLOUR = WHITE


CENTER = (MAX_X / 2, MAX_Y / 2)
AVERAGE_RADIUS = (MAX_RADIUS + MIN_RADIUS) / 2
