from colours import *

FPS = 30

MAX_X, MAX_Y = 1200, 700
BORDER = 100
BULLSEYE = 5

DEFAULT_COLOUR = WHITE
DEFAULT_RADIUS = 50
MAX_SPEED = 10

PALETTE = [RED, BLUE, YELLOW, GREEN, MAGENTA, CYAN]
NUM_COLOURS = 6